### ISSUE TITLE
Add to HACS

### ISSUE THREAD

**Issue by genebean** [widewing/ha-toyota-na#1]
Any chance you’d add this to HACS?

**Comment by widewing** [comment]
I'll do some homework later to see how to submit to HACS :)

**Comment by genebean** [comment]
Awesome, thank you! https://hacs.xyz/docs/publish/start should help.

**Comment by widewing** [comment]
it's in the waiting list:) https://github.com/hacs/default/pull/1175

**Comment by striebwj** [comment]
I installed it via HACS but I can't find the Toyota NA in the integrations, I might be wrong but is the custom component installed via HACS one directory too deep?

This is what I see for Toyota NA
<img width="266" alt="Screen Shot 2022-01-08 at 12 07 43 PM" src="https://user-images.githubusercontent.com/14165147/148653138-d1991f0e-4e76-477c-a493-3a3b46c06c7c.png">

But comparing to Spotcast, which only [shows the files in the custom component](https://github.com/fondberg/spotcast/tree/master/custom_components/spotcast) 
<img width="254" alt="Screen Shot 2022-01-08 at 12 09 58 PM" src="https://user-images.githubusercontent.com/14165147/148653210-a8d480ca-0d73-4662-8b88-07c8293a684a.png">

**Comment by 78hawkeye** [comment]
> I installed it via HACS but I can't find the Toyota NA in the integrations, I might be wrong but is the custom component installed via HACS one directory too deep?
> 
> This is what I see for Toyota NA <img alt="Screen Shot 2022-01-08 at 12 07 43 PM" width="266" src="https://user-images.githubusercontent.com/14165147/148653138-d1991f0e-4e76-477c-a493-3a3b46c06c7c.png">
> 
> But comparing to Spotcast, which only [shows the files in the custom component](https://github.com/fondberg/spotcast/tree/master/custom_components/spotcast) <img alt="Screen Shot 2022-01-08 at 12 09 58 PM" width="254" src="https://user-images.githubusercontent.com/14165147/148653210-a8d480ca-0d73-4662-8b88-07c8293a684a.png">

I think a few of us have had that happen. For me, it wasn’t showing up, Intried reboots, reinstalls, permissions, etc.,and eventually I gave up.  Then when I checked a little later on my iPhone, it was there as an integration just like it should have been. I went back to my laptop and force refreshed and it was there too, so it was either force refreshing the cached HA data, or something about waiting a bit for something to find it that worked for me.

**Comment by ksmarty** [comment]
I'm having the same issue

**Comment by widewing** [comment]
Now it's merged by HACS default repo.
@striebwj @ksmarty it should be fixed now.

**Comment by striebwj** [comment]
@widewing I'm having the issue even with the install directly from HACs not using the custom repo.

**Comment by widewing** [comment]
Which version did you install? Have you tried v1.0.3? I made a wrong zip package in previous version. @striebwj

**Comment by widewing** [comment]
interesting.. I don't have to choose beta releases.
