### ISSUE TITLE
Cannot connect to host oneapi.telematicsct.com

### ISSUE THREAD

**Issue by scsammyk** [widewing/ha-toyota-na#103]
The last two days my ha-toyota-na has stopped working. It fails to initialize and says:

“Failed setup, will retry: Cannot connect to host oneapi.telematicsct.com:443 ssl:default DNS server
returned answer with no data]”

At first I thought something happened with either the DNS server settings in home assistant or in my home network. After digging into that for a bit including changing my DNS server to 8.8.8.8 and updating home assistant from 2024.9.3 to 2024.12.3, I pinged oneapi.telematicsct.com from another computer on a separate network and it timed out. That makes me think it is something outside of my setup. Is anyone else having this problem?

![IMG_3158](https://github.com/user-attachments/assets/27d926d3-39d3-438c-9550-2566ff676cd9)

**Comment by winpplui** [comment]
There is a new version 2.5 that fix that issue
I removed my old version and installed the latest one, reboot, added my car and done

**Comment by scsammyk** [comment]
Thanks. Missed that! That fixed the issue
