### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by vanstinator** [widewing/ha-toyota-na#11]
I'm spinning up to contribute and realized there's not a great place to come together and chat in regards to reverse engineering and whatnot. To that end I'm setting up a discord server for both the NA and EU projects so we can collaborate and work together.

Feel free to join

https://discord.gg/mFHJYew658

**Comment by vanstinator** [comment]
I'll admin repo owners and maintainers

**Comment by widewing** [comment]
I put the link in the readme
