### ISSUE TITLE
Component activation improvements

### ISSUE THREAD

**Issue by jlmaners** [widewing/ha-toyota-na#18]
A few quality of life improvements for when a new user goes to activate the component in Home Assistant such that they receive error messages if something isn't going as planned. I wanted to jot these down for some of us to tackle at some point. 

- [ ] Check if vehicle is subscribed to remote services and post message back if not
- [ ] Check generation of vehicle's Entune to see which can be added safely

**Comment by dkmcgowan** [comment]
The latest version pulls the fields it can and does not add the ones it cannot based on subscription
