### ISSUE TITLE
Not Prompted for User/Pass with HACS

### ISSUE THREAD

**Issue by tehbra1n** [widewing/ha-toyota-na#19]
I'm able to install the integration through HACS, but I'm not prompted for a username/password.    Are the credentials supposed to be entered manually in a file in custom_components, or is there something else I'm missing?

**Comment by Xelinor** [comment]
You need to go to the home assistant integrations page now and add it there after installing it in HACS.

**Comment by tehbra1n** [comment]
Aha, thanks!
