### ISSUE TITLE
Moon Roof sensor created in error (Alpha 6)

### ISSUE THREAD

**Issue by Xelinor** [widewing/ha-toyota-na#31]
Upgraded to latest alpha build (2.0.0-alpha-6) and a new sensor was created in error: binary_sensor.moonroof_2021_highlander_hybrd

My Highlander does not have a moon roof.

If there are any error logs or anything you want, let me know and I can grab them.

**Comment by dkmcgowan** [comment]
Does this happen for others still?

**Comment by dkmcgowan** [comment]
Right now it can create sensors that the vehicle does not support, will look to add support to only create sensors that the vehicle supports at a later time.  For now just mark them disabled or hide them and then move on.
