### ISSUE TITLE
Remove support for smartKeyBatStatus and quantityOfEngOilStatus

### ISSUE THREAD

**Issue by jlmaners** [widewing/ha-toyota-na#34]
In looking to integrate these two sensors in the 2.0.0 release train, it appeared to me that these were never updated. 

After looking at sample results from several individuals `get_vehicle_health_status` calls via the toyota-na library, it appears these values all appear to show last updated dates of near the time the vehicle was manufactured/purchased or have no last update date listed.

I don't think these values are worth pulling in at this current time and shouldn't hold us up from moving forward with 2.0.0 becoming the stable release very shortly.

Would love an additional set of eyes on their own data to further validate.

**Comment by dkmcgowan** [comment]
These were removed
