### ISSUE TITLE
V2.0 not working on 2022.3.3

### ISSUE THREAD

**Issue by gui28347** [widewing/ha-toyota-na#35]
Just upgraded to 2022.3.3 and V2.0 and the error is now that all entities:
![image](https://user-images.githubusercontent.com/8279438/157950343-cdc16952-b361-4108-a5ab-3003c9169564.png)

How can I grab more details about the error ? 

Thanks,
Gui

**Comment by gui28347** [comment]
Error details: 
  return await self.api_request("GET", endpoint, header_params)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 35, in api_request
    return resp_json["payload"]
KeyError: 'payload'
2022-03-11 13:41:39 ERROR (MainThread) [custom_components.toyota_na] Error fetching toyota_na data: 'payload'

**Comment by vanstinator** [comment]
We just pushed a release that supports the diagnostic platform in HA. Navigate to the integrations page, select the menu on the `Toyota` integration, and click `Download Diagnostics`. The dump automatically redacts all sensitive information and will provide us with a lot more detail to help diagnose what's going on here.

**Comment by dkmcgowan** [comment]
If still a problem open a new issue
