### ISSUE TITLE
Door and Trunk status unavailable

### ISSUE THREAD

**Issue by adampoconnor** [widewing/ha-toyota-na#42]
[config_entry-toyota_na-afb2bdfb0dfa761af2e75ee844b671b2.json.txt](https://github.com/widewing/ha-toyota-na/files/8775369/config_entry-toyota_na-afb2bdfb0dfa761af2e75ee844b671b2.json.txt)

HomeAssistant says the status of my doors and windows is unavailable more recently. My trunk status never has been available. I just put in a fresh username and password following an HA restart.

Thanks

**Comment by dkmcgowan** [comment]
these entities should all eventually update, open new issue if something specific
