### ISSUE TITLE
[Enhancement] Add service to honk horn and specify climate during remote start

### ISSUE THREAD

**Issue by ACiDGRiM** [widewing/ha-toyota-na#45]
I've traded in my Subaru and the one feature I miss from that integration is being able to start a horn beep/flash lights and stop it. I have had my car robbed in my driveway twice, so I use this to scare away the riffraff that comes off the road.

It's also nice to be able to set the climate controls so in winter I can defrost the car and heat the cab, and in summer precool the car in summer, even if I had changed the controls while driving.

Thanks for making this available.

**Comment by dkmcgowan** [comment]
My vehicle does not support horn or climate so this is not something I can test or know if is available in the API
