### ISSUE TITLE
Can this integration continue as-is? (RE: DMCA takedown of `toyota_na`)

### ISSUE THREAD

**Issue by marcusrbrown** [widewing/ha-toyota-na#49]
Hi,

I use the Toyota mobile app and have a subscription to Remote Connect. After I provide my username and password, I get the following errors generated by the integration:

```
2022-10-02 22:43:28.944 ERROR (MainThread) [root] {"authId": "<REDACTED>", "callbacks": [{"type": "MetadataCallback", "output": [{"name": "data", "value": {"username": "<REDACTED>", "passwordretry": false}}], "_id": 10}, {"type": "PasswordCallback", "output": [{"name": "prompt", "value": "Prompt#E30B6C5085914D99AA4EF1C65A597674"}], "input": [{"name": "IDToken2", "value": ""}], "_id": 11}, {"type": "ChoiceCallback", "output": [{"name": "prompt", "value": "Prompt"}, {"name": "choices", "value": ["continue", "resetpass"]}, {"name": "defaultChoice", "value": 0}], "input": [{"name": "IDToken3", "value": 0}], "_id": 4}]}
2022-10-02 22:43:28.947 ERROR (MainThread) [custom_components.toyota_na.config_flow] Not logged in
```

I looked at a few other issues and logged into the Toyota site in a browser, as suggested in #22. After removing and reinstalling the integration, the result is the same. I'm assuming this error (`tokenId` isn't available) is the flow for MFA, which hasn't been implemented in the client library.

Wanting to dig further at the source, I went to pull up the source of the [toyota-na client library](https://github.com/toyotha/toyota-na) used by this integration, to find that it has been pulled from GitHub via [DMCA takedown](https://github.com/github/dmca/blob/master/2022/09/2022-09-20-toyota.md).

I downloaded `toyota_na` 2.1.1, which contains an API key embedded in the source, which is why Toyota filed the takedown. What does this mean for the future of this integration? Is it possible to remove the hardcoded API key and leave its retrieval as "an exercise for the reader"? I want to help with implementing MFA if the library can be restored.

**Comment by danepowell** [comment]
I'm similarly concerned, but just to note, I just installed this integration for the first time via HACS and it seems to work great out of the box, despite the toyota-na library being AWOL. So maybe there's not a hard dependency?

**Comment by omar10wahab** [comment]
> Hi,
> 
> I use the Toyota mobile app and have a subscription to Remote Connect. After I provide my username and password, I get the following errors generated by the integration:
> 
> ```
> 2022-10-02 22:43:28.944 ERROR (MainThread) [root] {"authId": "<REDACTED>", "callbacks": [{"type": "MetadataCallback", "output": [{"name": "data", "value": {"username": "<REDACTED>", "passwordretry": false}}], "_id": 10}, {"type": "PasswordCallback", "output": [{"name": "prompt", "value": "Prompt#E30B6C5085914D99AA4EF1C65A597674"}], "input": [{"name": "IDToken2", "value": ""}], "_id": 11}, {"type": "ChoiceCallback", "output": [{"name": "prompt", "value": "Prompt"}, {"name": "choices", "value": ["continue", "resetpass"]}, {"name": "defaultChoice", "value": 0}], "input": [{"name": "IDToken3", "value": 0}], "_id": 4}]}
> 2022-10-02 22:43:28.947 ERROR (MainThread) [custom_components.toyota_na.config_flow] Not logged in
> ```
> 
> I looked at a few other issues and logged into the Toyota site in a browser, as suggested in #22. After removing and reinstalling the integration, the result is the same. I'm assuming this error (`tokenId` isn't available) is the flow for MFA, which hasn't been implemented in the client library.
> 
> Wanting to dig further at the source, I went to pull up the source of the [toyota-na client library](https://github.com/toyotha/toyota-na) used by this integration, to find that it has been pulled from GitHub via [DMCA takedown](https://github.com/github/dmca/blob/master/2022/09/2022-09-20-toyota.md).
> 
> I downloaded `toyota_na` 2.1.1, which contains an API key embedded in the source, which is why Toyota filed the takedown. What does this mean for the future of this integration? Is it possible to remove the hardcoded API key and leave its retrieval as "an exercise for the reader"? I want to help with implementing MFA if the library can be restors there any update to this?

> Hi,
> 
> I use the Toyota mobile app and have a subscription to Remote Connect. After I provide my username and password, I get the following errors generated by the integration:
> 
> ```
> 2022-10-02 22:43:28.944 ERROR (MainThread) [root] {"authId": "<REDACTED>", "callbacks": [{"type": "MetadataCallback", "output": [{"name": "data", "value": {"username": "<REDACTED>", "passwordretry": false}}], "_id": 10}, {"type": "PasswordCallback", "output": [{"name": "prompt", "value": "Prompt#E30B6C5085914D99AA4EF1C65A597674"}], "input": [{"name": "IDToken2", "value": ""}], "_id": 11}, {"type": "ChoiceCallback", "output": [{"name": "prompt", "value": "Prompt"}, {"name": "choices", "value": ["continue", "resetpass"]}, {"name": "defaultChoice", "value": 0}], "input": [{"name": "IDToken3", "value": 0}], "_id": 4}]}
> 2022-10-02 22:43:28.947 ERROR (MainThread) [custom_components.toyota_na.config_flow] Not logged in
> ```
> 
> I looked at a few other issues and logged into the Toyota site in a browser, as suggested in #22. After removing and reinstalling the integration, the result is the same. I'm assuming this error (`tokenId` isn't available) is the flow for MFA, which hasn't been implemented in the client library.
> 
> Wanting to dig further at the source, I went to pull up the source of the [toyota-na client library](https://github.com/toyotha/toyota-na) used by this integration, to find that it has been pulled from GitHub via [DMCA takedown](https://github.com/github/dmca/blob/master/2022/09/2022-09-20-toyota.md).
> 
> I downloaded `toyota_na` 2.1.1, which contains an API key embedded in the source, which is why Toyota filed the takedown. What does this mean for the future of this integration? Is it possible to remove the hardcoded API key and leave its retrieval as "an exercise for the reader"? I want to help with implementing MFA if the library can be restored.

Is there any update to this? I would hate to see such a great integration tossed away so easily

**Comment by dkmcgowan** [comment]
The integration will work as long as the API does not change, the code from referenced library taken down are not in this integration
