### ISSUE TITLE
Integration will fail on 2023.3

### ISSUE THREAD

**Issue by danepowell** [widewing/ha-toyota-na#53]
Been seeing this in my logs recently:

> Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for toyota_na using this method at custom_components/toyota_na/__init__.py, line 57: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by ACiDGRiM** [comment]
This is devastating

**Comment by tacerra** [comment]
It's an easy fix, just change

this (line  57 in /config/custom_components/toyota_na/__init__.py)
**hass.config_entries.async_setup_platforms(entry, PLATFORMS)**

to
**await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)**

**Comment by widewing** [comment]
Thanks! Fixed in v2.1.3.
