### ISSUE TITLE
Certain windows show as "unavailable"

### ISSUE THREAD

**Issue by CamSoper** [widewing/ha-toyota-na#54]
My rear windows showed their status when I first set up this integration, but at some point they stopped. Same for moonroof.

![image](https://user-images.githubusercontent.com/137648/236292687-c49a3bfb-a66c-495e-963d-262668d3baa9.png)

**Comment by jgdf42** [comment]
my trunk status shows as unavailable..

**Comment by atflack** [comment]
22 4Runner here. All windows, including trunk window, show unavailable.

**Comment by dkmcgowan** [comment]
these should eventually update

**Comment by atflack** [comment]
No, they don’t. I’ve had this integration active since March. The windows have not once switched from unavailable.

**Comment by dkmcgowan** [comment]
I can add some additional info in diagnostics and see if we can tell what's happening

**Comment by dkmcgowan** [comment]
Update to v2.4.3 and go to the integration and do "Download Diagnostics" and let me see that file and maybe I can figure out why they are all unavailable

**Comment by atflack** [comment]
Attached, thanks!
[config_entry-toyota_na-4cc05426605b404987beb37e4c5c5a74.json](https://github.com/user-attachments/files/17190807/config_entry-toyota_na-4cc05426605b404987beb37e4c5c5a74.json)

**Comment by dkmcgowan** [comment]
Looking over that API response your window status just isn't there, in the vehicle_status section next to the Doors that are listed you should have nodes for Window and you don't, not sure what we could do here if it doesn't return from their API

**Comment by atflack** [comment]
Playing with the Toyota app, I’m also not getting it to flip from a Windows – Closed state. Wondering if this is a Toyota bug. I’m going to look for a way to open a ticket with them.

**Comment by dkmcgowan** [comment]
I would only talk to them about issues you are having in their official app and not home assistant.

**Comment by atflack** [comment]
Yup, just opened a ticket. That’s how I approached it, the Toyota app isn’t reflecting the correct status.

**Comment by dkmcgowan** [comment]
If you still have an issue with the latest version and after hearing back from Toyota then open a new issue, good luck!
