### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by jgdf42** [widewing/ha-toyota-na#57]
Originally made my account using google authentication. When I try to make an account now, it won't let me because I'm using that email via google auth. Created an account via phone number (created a password atnthis stage) and it auto linked to my google authed account and pulled in all my info, but neither phone or email with the password I made work.

Possible to add authentication via google login as the Toyota app allows?

Also, discord link on github is dead.

**Comment by Gd1230** [comment]
Having the same login issue. This worked just a few months ago. Guessing Toyota changed something

**Comment by sbailey151** [comment]
Same… :(

**Comment by davidr521** [comment]
Same. Any update? 🤷‍♂️

**Comment by frostedcore** [comment]
Go to this thread and follow this comments advice.  I just got up with it a day ago using these steps.

https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1585224248

**Comment by sbailey151** [comment]
> Go to this thread and follow this comments advice. I just got up with it a day ago using these steps.
> 
> [#52 (comment)](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1585224248)

I appreciate the link, but I'm lost on how to implement this fix.  :(

**Comment by ryanandres** [comment]
> > Go to this thread and follow this comments advice. I just got up with it a day ago using these steps.
> > 
> > [#52 (comment)](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1585224248)
> 
> I appreciate the link, but I'm lost on how to implement this fix.  :(

You'll need to ssh the host. See https://community.home-assistant.io/t/sshing-from-a-command-line-sensor-or-shell-command/258731

After you run
> docker exec -it homeassistant bash

Then you can run the commands from the other thread

**Comment by omar10wahab** [comment]
> > > Go to this thread and follow this comments advice. I just got up with it a day ago using these steps.
> > > [#52 (comment)](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1585224248)
> > 
> > 
> > I appreciate the link, but I'm lost on how to implement this fix.  :(
> 
> You'll need to ssh the host. See https://community.home-assistant.io/t/sshing-from-a-command-line-sensor-or-shell-command/258731
> 
> After you run
> 
> > docker exec -it homeassistant bash
> 
> Then you can run the commands from the other thread

tried this and keep getting login error and ive double checked the user and password by logging into the app. Not sure if i need to do something formatting wise when entering the user and pass? Please help

**Comment by omar10wahab** [comment]
> > Go to this thread and follow this comments advice. I just got up with it a day ago using these steps.
> > [#52 (comment)](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1585224248)
> 
> I appreciate the link, but I'm lost on how to implement this fix. :(

Did you ever figure out how to get this to work?

**Comment by Bosty01** [comment]
Looks like it has died if you are installing it now. Not using docker so the fix won't work for me.

**Comment by omar10wahab** [comment]
> Looks like it has died if you are installing it now. Not using docker so the fix won't work for me.

You don't need to use docker and I would suggest not attempting it that way because people have mentioned in other threads it's a solution you will have to utilize after every HA update I believe. Utilizing a computer to run the code using the API specified, it'll generate a json file that you copy the contents into a file in home assistant. There are some issues with running the API initially so there's instructions on how to modify the API to allow you to run it. This solution worked for me though. I did attempt to do docker method and failed but maybe to my own fault and lack of knowledge. I would highly advise using this comment to attempt this fix.

https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1540831221

**Comment by Bosty01** [comment]
> > Looks like it has died if you are installing it now. Not using docker so the fix won't work for me.
> 
> You don't need to use docker and I would suggest not attempting it that way because people have mentioned in other threads it's a solution you will have to utilize after every HA update I believe. Utilizing a computer to run the code using the API specified, it'll generate a json file that you copy the contents into a file in home assistant. There are some issues with running the API initially so there's instructions on how to modify the API to allow you to run it. This solution worked for me though. I did attempt to do docker method and failed but maybe to my own fault and lack of knowledge. I would highly advise using this comment to attempt this fix.
> 
> [#52 (comment)](https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1540831221)

ok, thanks for this. I'll see what I can do to make this work.
