### ISSUE TITLE
automating based on driving/parked?

### ISSUE THREAD

**Issue by jtaseff** [widewing/ha-toyota-na#58]
I can't figure out a good way to automate based on whether the car is driving/running/stopped. Is there any useful data that can be returned, or data already there that can be automated on? Is there some trick to trigger on the odometer changing to any value for a certain period? It wants me to add an "above" value.

So far all I've gotten to work is a proximity sensor to automate on when the car arrives to certain zones, but it's not great for generic like knowing when it was parked at a random store.

**Comment by dkmcgowan** [comment]
There is a new speed value added in v2.4 you could try, but location not changing for a period is also a good way to know of the r
