### ISSUE TITLE
Canada not supported?

### ISSUE THREAD

**Issue by klein1jo** [widewing/ha-toyota-na#60]
Is Canada not supported?  Last I checked Canada is part of North America.  Error is "Invalid UI Locale provided".   Locale is set to Canada.

{"authId": "", "callbacks": [{"type": "TextOutputCallback", "output": [{"name": "message", "value": "Invalid UI Locale provided"}, {"name": "messageType", "value": "2"}]}]}

**Comment by maxistviews** [comment]
Was this the case? How did you solve this?

**Comment by klein1jo** [comment]
It was not the case.  Had to do with the DMCA takedown and the toyota-na project being dropped just like everyone else.  I followed https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1540831221.  FWIW I'm running the Home Assistant Docker image.
