### ISSUE TITLE
Cant Log In

### ISSUE THREAD

**Issue by Yodie98** [widewing/ha-toyota-na#64]
I get the integration installed via HACS, and when I put in my email and pass, it just errors out and says, 'Not Logged In.'

The email and pass work for both the Toyota Website and app. Not sure what's happening

**Comment by motox986** [comment]
You have to do some editing to the auth.py file within the toyota-na client you download form pypi.


Read through here to get an idea if it's something you want to tackle. Specifically JiDoans comments and further ones below.

https://github.com/widewing/ha-toyota-na/issues/52#issuecomment-1519291342

**Comment by dkmcgowan** [comment]
this was resolved in v2.2.1 and still working in v2.4.0
