### ISSUE TITLE
HA Toyota_NA Log Warnings

### ISSUE THREAD

**Issue by tmorris0221** [widewing/ha-toyota-na#68]
Hello,

I'm seeing the following entries in my HA logs regarding some deprecated constants. Is there anyone that could update the integration to update to the new values?

Logger: homeassistant.const
Source: helpers/deprecation.py:206
First occurred: 7:33:17 AM (4 occurrences)
Last logged: 7:33:27 AM

LENGTH_MILES was used from toyota_na, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please report it to the author of the 'toyota_na' custom integration
PRESSURE_PSI was used from toyota_na, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.PSI instead, please report it to the author of the 'toyota_na' custom integration
LENGTH_KILOMETERS was used from toyota_na, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please report it to the author of the 'toyota_na' custom integration

Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:206
integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 7:33:26 AM (2 occurrences)
Last logged: 7:33:26 AM

SOURCE_TYPE_GPS was used from toyota_na, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please report it to the author of the 'toyota_na' custom integration

**Comment by widewing** [comment]
resolved by v2.2.1
