### ISSUE TITLE
Reporting EV range and Traction Battery state?

### ISSUE THREAD

**Issue by rfrush** [widewing/ha-toyota-na#69]
I note that the "Distance to Empty" sensor only report the "HV" range, and excludes the EV range.   I also note that the Traction battery state of charge is not reported.  The Toyota App reports these fields, which suggests that the API supports them.  Is this an easy fix to update?

**Comment by civita** [comment]
Looks like it's been discussed here #16

**Comment by gokou340** [comment]
It was discussed and someone was able to do it, but couldn't provide any of the code.

I would love to get EV Charge and EV Range in this.

**Comment by dkmcgowan** [comment]
I added support in https://github.com/widewing/ha-toyota-na/pull/75

**Comment by dkmcgowan** [comment]
The latest version v2.4.0 adds electric vehicle status
