### ISSUE TITLE
[FR] Create Binary Sensors for Door, Window, Hatch State and Locks

### ISSUE THREAD

**Issue by stephengolub** [widewing/ha-toyota-na#7]
It'd be ideal to have the doors, windows, hatch/trunk and their lock status as binary sensors instead of just plane text sensors.

**Comment by widewing** [comment]
Understand. However it's not very straightforward to enumerate all sections/status text from the API. 
You can take a look at the sample at: https://github.com/widewing/toyota-na/blob/master/samples/vehicle_status.json
The lock status is provided as text, the sections not always door/window etc but could be trip status. And there might be difference among different vehicles.

**Comment by stephengolub** [comment]
First off, thanks for putting this together, I was wanting this for a while.

Second, there are actually two locations you can pull this from. The existing "vehicle status" endpoint y'all have, I've got a PR using that incoming.

But looking at the "vehicle detail" endpoint, it looks like the `.payload.vehicle.remoteServicesExceptions` could just be enumerated into binary sensors.

For example
```json
{
  "name": "rearPassengerDoorLockStatus",
  "value": "Y"
}
```

That could be set as: `binary_sensor.rear_passenger_door_lock_status` and the state evaluated from `value == 'Y'`

The catch here is that these are "exceptions" and therefore are saying "is this status in a good state". But doors and windows are open when these are in a bad state, and locks are unlocked when in a bad state.

Therefore the full logic would be:

`return True if self.device_class == 'lock' and value.upper() == 'Y' or value.upper() == 'N'`

Wherein you set the `device_class` value from looking for `lock`, `window` or `door` in the `name` field.

**Comment by widewing** [comment]
But from my observation, the items under `vehicle.remoteServicesExceptions` never change according the door status. Whatever the real status is, all of them are "Y" except for "hazard" which is "N".

**Comment by stephengolub** [comment]
> Whatever the real status is, all of them are "Y" except for "hazard" which is "N".

Good to know. Sounds like some more testing on that endpoint is needed.

**Comment by vanstinator** [comment]
This has been implemented in https://github.com/widewing/ha-toyota-na/issues/29

**Comment by stephengolub** [comment]
Yep. I've installed the alpha and confirm that this is functioning!
