### ISSUE TITLE
Getting '400 Bad Request' Message with previously-working entities

### ISSUE THREAD

**Issue by davidr521** [widewing/ha-toyota-na#82]
Getting a message from the integration of "Failed Setup, will retry: 400, message='Bad Request', url='https://oneapi.telematicsct.com/v1/global/remote/status'."

Prior to last weekend, this worked fine.

**Comment by HMGOMEZ77** [comment]
Same here.. I am not able to get this to work

**Comment by nishithdev** [comment]
Same here

**Comment by dkmcgowan** [comment]
Go to the integration and do the download diagnostics and post the json file here

**Comment by davidr521** [comment]
> Go to the integration and do the download diagnostics and post the json file here

Sincere apologies, but I don't see where that's an option on the integration - neither the integration nor the devices list the option to "download diagnostics...?"

I'll keep looking, but if any of you know the simplest way to do so, happy to do that here

**Comment by dkmcgowan** [comment]
Click on settings, devices, scroll to integration and click it, not the device, but the integration itself.  Then you will see the 3 dots, click that, then download diagnostics

**Comment by davidr521** [comment]
That's what I'm saying. It doesn't appear next to them. See below:
![Toyota Integration](https://github.com/user-attachments/assets/ad23ad3f-0f85-4638-ac2b-5e84dff9655a)

**Comment by dkmcgowan** [comment]
I guess you can't run it unless the integration is successfully setup

**Comment by davidr521** [comment]
> I guess you can't run it unless the integration is successfully setup

Appears to be...therein lies the rub.

Can anyone else on this thread do so?

**Comment by dkmcgowan** [comment]
Go to system logs and view full log and post the entire stack trace instead of the small message you get from the preview

**Comment by davidr521** [comment]
Is this what you're after?

This error originated from a custom integration.

Logger: custom_components.toyota_na
Source: custom_components/toyota_na/__init__.py:159
integration: Toyota (North America) (documentation, issues)
First occurred: 8:53:28 AM (632 occurrences)
Last logged: 4:00:58 PM

Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 159, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/config/custom_components/toyota_na/patch_seventeen_cy_plus.py", line 80, in update
    vehicle_status = await self._client.get_vehicle_status(self._vin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
    return await self.get_vehicle_status_17cyplus(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
    return await self.api_get("v1/global/remote/status", {"VIN": vin})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://oneapi.telematicsct.com/v1/global/remote/status'

**Comment by dkmcgowan** [comment]
Give v2.4.5 a try, just published it, I added some exception handling to see if it will get further.  The vehicle status API call is failing for you and it shouldn't, but let's see if this gets further.  I would delete both of those integrations and start over.

**Comment by HMGOMEZ77** [comment]
2.4.6 release worked..it didn't give me the bad request error. But I do not
see any identity or device under the integration

**Comment by dkmcgowan** [comment]
I just had it continue past errors so I can see more.  Now go to the integration and download diagnostics and send me the json file

**Comment by HMGOMEZ77** [comment]
now Home Assistant crashes and cannot access it.. I have to reboot and it
will work for a few mins then crash again

**Comment by davidr521** [comment]
> I just had it continue past errors so I can see more. Now go to the integration and download diagnostics and send me the json file

So now it succeeds for my _wife's_ vehicle, but fails for mine...?

Should I try removing and re-adding it first? Or send you diagnostics first? Or...

**Comment by bmitchell76** [comment]
after the update, I'm getting 500 error, and before it was a 400.

aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://oneapi.telematicsct.com/v2/legacy/remote/status'
2024-10-03 05:33:57.830 ERROR (MainThread) [custom_components.toyota_na] Error fetching data

aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://oneapi.telematicsct.com/v1/global/remote/status'
2024-10-02 06:01:11.938 ERROR (MainThread) [custom_components.toyota_na] Error fetching data

**Comment by bmitchell76** [comment]
2024-10-03 09:06:55.678 ERROR (MainThread) [custom_components.toyota_na] Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 159, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/usr/local/lib/python3.12/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy.py", line 86, in update
    vehicle_status = await self._client.get_vehicle_status(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 65, in get_vehicle_status
    return await self.get_vehicle_status_17cy(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 75, in get_vehicle_status_17cy
    return await self.api_get(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://oneapi.telematicsct.com/v2/legacy/remote/status'
2024-10-03 09:06:55.681 DEBUG (MainThread) [custom_components.toyota_na] Finished fetching toyota_na data in 2.765 seconds (success: False)

**Comment by dkmcgowan** [comment]
The more json diagnostic files I can get with these exceptions the better, I cannot do much with just the stack trace.  It seems for some vehicles you can't get the vehicle status, do your cars support remote start?  Maybe that API doesn't work for all vehicles and fails poorly.

As for the issue with home assistant crashing, go in and remove the integration and see if it stops, not sure what in the change I made would cause a crash, it shouldn't

**Comment by bmitchell76** [comment]
neither of my vehicles have remote start

**Comment by dkmcgowan** [comment]
Ok, I bet I can read that from the vehicle details and then not make those calls at all if not supported and maybe it cleans some of this up, will work on that tonight

**Comment by HMGOMEZ77** [comment]
thanks a lot for all your help and hard work to get this resolved

**Comment by davidr521** [comment]
Yes - thanks indeed!

**Comment by HMGOMEZ77** [comment]
Turns out my HA crashing wasn't related to the Toyota integration..It was
the Alexa integration..sorry for the confusion this may have caused you..

**Comment by dkmcgowan** [comment]
There still isn't much I can see without the full download of diagnostics, that is not the same as just a copy/paste from the log file, that is going to the integration, clicking the 3 dots next to the integration, doing download diagnostics, which creates a "json" file on your laptop, which you need to upload here and post for me to review the full API responses not just these exceptions

**Comment by dkmcgowan** [comment]
I created a new version, v2.4.7, it will still log the exceptions for me but also continue, but I still need the full diagnostic download, not just the log information.  I think there may be another car type and json format and I need to see it before I could try to fix it.

**Comment by bmitchell76** [comment]
[config_entry-toyota_na-01J98VMXA75PX51CH1K0F0DXPR.json](https://github.com/user-attachments/files/17256980/config_entry-toyota_na-01J98VMXA75PX51CH1K0F0DXPR.json)

Thank you, I have no logon errors but also no entities.  I can see in the JSON it's finding my vehicle, this is promising.

**Comment by dkmcgowan** [comment]
Did you have some errors in the system log as well?  If so post those also, but you don't have a vehicle status node and it's likely because it shows your subscription status as UNKNOWN, do you pay for remote access subscription?  Without that this doesn't work

**Comment by bmitchell76** [comment]
Yes, I have two vehicles, no sub for the Rav4 and under a trial sub for the Carolla.

2024-10-04 10:05:36.515 INFO (MainThread) [custom_components.toyota_na] Tokens refreshed, updating ConfigEntry
2024-10-04 10:05:36.518 DEBUG (MainThread) [custom_components.toyota_na] Updating vehicle status
2024-10-04 10:05:38.811 ERROR (MainThread) [custom_components.toyota_na.patch_seventeen_cy_plus] 400, message='Bad Request', url='https://oneapi.telematicsct.com/v1/global/remote/status'
2024-10-04 10:05:39.668 ERROR (MainThread) [custom_components.toyota_na.patch_seventeen_cy_plus] 400, message='Bad Request', url='https://oneapi.telematicsct.com/v1/global/remote/engine-status'
2024-10-04 10:05:40.411 ERROR (MainThread) [custom_components.toyota_na.patch_seventeen_cy] 500, message='Internal Server Error', url='https://oneapi.telematicsct.com/v2/legacy/remote/status'
2024-10-04 10:05:41.526 ERROR (MainThread) [root] Error parsing response: {"status":"SUCCESS","code":200,"message":"Ok","errors":[]}
2024-10-04 10:05:41.528 ERROR (MainThread) [custom_components.toyota_na.patch_seventeen_cy] 'payload'
2024-10-04 10:05:41.836 WARNING (MainThread) [custom_components.toyota_na] Your 2022 COROLLA HYBRID LE SEDAN needs a remote services subscription to be used with Home Assistant.
2024-10-04 10:05:41.836 WARNING (MainThread) [custom_components.toyota_na] Your 2019 RAV4 HYBRID LE AWD SUV needs a remote services subscription to be used with Home Assistant.
2024-10-04 10:05:41.837 DEBUG (MainThread) [custom_components.toyota_na] Finished fetching toyota_na data in 5.318 seconds (success: True)

**Comment by bmitchell76** [comment]
what's odd, for the Carolla, in the JSON, I can see the tire PSI, so it's getting something.

**Comment by dkmcgowan** [comment]
I will see why the tire entities didn't create at least, also see if any errors in the system log you can post to add with the json

**Comment by HMGOMEZ77** [comment]
I also have have a trial sub.. I can see the status on the toyota app. Tire
pressure

**Comment by MitchBaker** [comment]
I just opened another thread, but then found this one.  

Fresh install here - and I am able to download the diagnostics - and on looking into the diagnostics json - I see all the informaiton I am looking for - Fuel level, Odometer, Tire pressure....   Just not available to Home Assistant.

@dkmcgowan Let me know best way to get the diagnostics to you if you are interested.

**Comment by MitchBaker** [comment]
> You can just upload it here, it should have sensitive things redacted

[DiagnosticDownload.json](https://github.com/user-attachments/files/17262726/DiagnosticDownload.json)

**Comment by davidr521** [comment]
Not sure if it helps any, but I have subscriptions for both vehicles.

My wife’s shows up, but mine does not.

[Dave Rosenblatt - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2stt4q)	[2stt4q]

On October 4, 2024 at 18:55 GMT, MitchBaker ***@***.***> wrote:

You can just upload it here, it should have sensitive things redacted

[DiagnosticDownload.json](https://github.com/user-attachments/files/17262726/DiagnosticDownload.json)

**Comment by dkmcgowan** [comment]
I can probably make it create the entities and populate what it can with a fix, but yours shows remote subscription INACTIVE and the "vehicle_status" node at the bottom empty, which is where a lot of the information that is useful comes from, so looks like you have have subscription for some things, but not remote subscription which is all the doors, windows status, remote turn on engine, etc..

**Comment by MitchBaker** [comment]
My main things I wanted to track was Odometer, Fuel, and Tire pressure.

Last parked location was redacted, so unsure if that gets reported without a subscription.  

I did try the remote subscription - but was informed after a ton of back and forth that my vehicle didn't support the remote functions such as window status, remote engine turn on etc.  so I cancelled it (the only "benefit" would have been navigation, but that's better with Waze through android auto anyway)

**Comment by bmitchell76** [comment]
There are multiple tiers of subscriptions, but all subscriptions include remote connect which should include the basic things, odometer, fuel, and tire pressure.

**Comment by MitchBaker** [comment]
The JSON says my corolla is capable of those things I wanted (even though Toyota support said it didn't when it didn't show in the app).  Hell, if this gave me the capability to use those items even if Toyota app didn't I may actually pay Toyota for the subscription.

**Comment by bmitchell76** [comment]
if we (@dkmcgowan) get it working, I will pony up and subscribe to both of my cars.

**Comment by dkmcgowan** [comment]
Try the latest version v2.4.8, I removed some subscription restrictions so it should attempt to create all the entities it can and just make the ones it cannot unavailable

**Comment by HMGOMEZ77** [comment]
It works!! I can see the Tire pressure sensors, fuel gauge,  service, etc..

**Comment by bmitchell76** [comment]
It works for me too.  I can see both cars, the one without the sub shows all entities as unavailable.  The one with the trial sub shows all possible entities, the basic ones that the car/sub is capable of pulling back correctly but things the car/sub aren't capable of show as unavailable.  For example, it's not an EV but shows charging status as unavailable and door controls as unavailable.

But 100% I can see tire pressure, fuel, odometer, and location.

@dkmcgowan, thanks for all the work you've put into this.

**Comment by bmitchell76** [comment]
It's also showing the speed in km/h not mi/h.

**Comment by MitchBaker** [comment]
Good to go here, any available statuses are shown in home Assistant. Thank you very much for your effort!

**Comment by dkmcgowan** [comment]
Great!  I plan to clean up some of the code and make the unavailable not be created when I know they are not available like electric and due to the subscription, which will clean it up more.  I think I will remove speed, I don't think it updates, I checked it and didn't seem to work from their API, might be why they don't show it in their own Toyota app

**Comment by bmitchell76** [comment]
Thanks agin!  Speed does show up for me.![image](https://github.com/user-attachments/assets/6eef6c4e-572f-48af-b392-625b7505558d)

**Comment by dkmcgowan** [comment]
I will leave speed then.  It seems to only come back as km/h so if someone wants to change it for now just make a new template sensor and you could convert it, I can see about doing that in the integration later also

**Comment by bmitchell76** [comment]
I created a template sensor and that does the job.

{{ (states('sensor.speed_2022_corolla_hybrid_le_sedan') | float / 1.609344) | round(0) }}

![image](https://github.com/user-attachments/assets/2e6f9bc3-25eb-4f4d-9adc-d866dfa4bd8b)

**Comment by davidr521** [comment]
What’s weird on mine is now I see _some_ of the sensors created, but several are not.   
  

  
Please note, my wife and I have the same subscription, and we can see 100% of her info just fine.   
  

  
Other than upgrading the version of this integration, I haven’t changed anything.   
  
  
  
  
  
  
  

  
  
>

**Comment by dkmcgowan** [comment]
I need the json output from download diagnostics and tell me which car was working and which one wasn't so I can look it over

**Comment by dkmcgowan** [comment]
I released v2.4.9, this should no longer create entities when you do not have a subscription, for existing setups you will need to delete them but they will no longer show for everyone as unavailable.  The parking and real time location were swapped for some vehicles as well.  This should also call fewer API's when they will knowingly fail.

**Comment by bmitchell76** [comment]
@dkmcgowan, thanks again for the work you put into this! It's much appreciated.

**Comment by bmitchell76** [comment]
Observation, yesterday when the entities not included with my car/sub were unavailable there was a control to lock the doors.  That control didn't work, but it did show the door lock status.  Can the door lock status be added as a sensor?

**Comment by dkmcgowan** [comment]
I'm not sure that status was accurate though for you, create me a json diagnostics download and let me review your file and see if there is a lock status for non subscription users I can use to make a new sensor

**Comment by bmitchell76** [comment]
Thanks again!  here you go.
[config_entry-toyota_na-01J9GXJ95TXWW42DS3SERVSEE0.json](https://github.com/user-attachments/files/17270842/config_entry-toyota_na-01J9GXJ95TXWW42DS3SERVSEE0.json)

**Comment by dkmcgowan** [comment]
Unfortunately there isn't a lock status in there for you, it's part of the "vehicle_status" section that only comes back when you have a subscription

I'm going to close out this issue as the original one I think we closed, but open a new issue if new problems or more information shows up!

**Comment by bmitchell76** [comment]
Thanks for trying

**Comment by davidr521** [comment]
Thanks @dkmcgowan for fixing!

**Comment by HMGOMEZ77** [comment]
Good afternoon,  Can you take a look at the integration. It's not pulling
any entities
