### ISSUE TITLE
2023 Prius Prime Doesn't Show Remote Start Service

### ISSUE THREAD

**Issue by caldorf** [widewing/ha-toyota-na#84]
My 2023 Prius Prime has full support for remote start, I use it via the Toyota App to heat up/cool down my car. Unfortunately, that is not showing up as an available service in Home Assistant and I would really like to use that, especially since it is shown as a feature of this integration. In fact non of the [4 services listed](https://github.com/widewing/ha-toyota-na/tree/v2.4.7) are available other than Lock/Unlock.

Thank you so much!

**Comment by dkmcgowan** [comment]
That's odd, I see all those services listed.  It does not currently have head up/cool down services, I don't have that support in my car so I can't test it but can try to see if I could add it.  If you go to developer tools and actions and do "toyota_na." you only see lock/unlock?  You are running the latest version?

**Comment by caldorf** [comment]
Yup! Latest version and I only see unlock. And by heat up and cool down I mean remote start the car and by doing that it turns on the AC, it should just be the remote start service 

![services](https://github.com/user-attachments/assets/772b7ba0-ee0b-49b8-b93a-32b083c648f9)
![version](https://github.com/user-attachments/assets/febfc35c-6b02-406e-9adf-db9ed6273988)

**Comment by caldorf** [comment]
After further review, it looks like I can run the Toyota:Engine_Start service manually and that worked! However, it might be a good idea to put that as a button within the controls section.

Also, the Plug Status sensor uses what seems to be arbitrary values. From what I can tell:
- 45=Done Charging but plugged in
- 40=Charging
- 12=Unplugged

Either way, this is working for me so I will now mark this as resolved thank you!

**Comment by dkmcgowan** [comment]
Nice on plug status, I knew about 12 but not the others yet, that's how it comes from Toyota, I can turn it into an enum.  I left this services because it's hard to guarantee state, so an on/off button or toggle could easily be off, so for me I just made 2 buttons for engine start and engine stop and they call the service, just like the Toyota app.

**Comment by jcmags91** [comment]
@dkmcgowan How did you go about making those buttons, as it currently only have the ability to lock or unlock. I would like to be able to remote start as well. As @caldorf said I can call the service manually thru the developer options but would like to toggle or button. Thanks.
