### ISSUE TITLE
Last Parked Location - Title Incorrect

### ISSUE THREAD

**Issue by Airey001** [widewing/ha-toyota-na#87]
The Last Parked Location Sensor should be renamed as just location or Last Known Location.  When the vehicle is running this is updated every 2 minutes giving you the Vehicles Last know location.

**Comment by dkmcgowan** [comment]
I noticed that as well, the "Current Location" and "Last Parked Location" are swapped, will push an update

**Comment by dkmcgowan** [comment]
I just pushed a new release v2.4.10 that should fix this
