### ISSUE TITLE
Question (not a bug)

### ISSUE THREAD

**Issue by Geezus42** [widewing/ha-toyota-na#89]
Apologies if there is a better place to ask this.

How can I retrieve this information outside of HA?

I would normally assume that I could use the underlying python application, except that it's readme says it does not support North America. Are you using a custom unpublished variant?

I would like to be able to play with it and use some of the features from the command line. Especially right now while I rebuild my HA.

**Comment by dkmcgowan** [comment]
The project is no longer on git as it was shutdown by Toyota, it contained secrets and they shut it down.  The package is still on pypi so if you want to pip install the toyota-na package and go find the code there, it has an application you can run and play with.  It is outdated so you might look at this projects patch files to see where you could make it work better.  Will leave it at that and don't want to discuss that root package here as it got shutdown.

**Comment by Geezus42** [comment]
Excellent, thank you!
